version: '3'
services:
  eureka-server:
    image : registry
    ports:
      - 8888:8888

  gateway-service:
    image : apig
    depends_on :
      - eureka-server
    ports:
      - 7777:7777
    environment:
      PROFILE: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka/"
    restart: on-failure

  ms-formation-service:
    image: ms-formation
    depends_on :
      - eureka-server
      - gateway-service
    environment:
      PROFILE: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka/"
    ports:
      - 8090:8090
    restart: on-failure

  ms-scolarite-service:
    image: ms-scolarite
    depends_on :
      - eureka-server
      - gateway-service
    environment:
      PROFILE: "default"
      eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka/"
    ports:
      - 8082:8082
    restart: on-failure
